"""empty message

Revision ID: 7ca929ea9cb7
Revises: 
Create Date: 2019-06-28 18:59:14.903010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca929ea9cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_log',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_ip', sa.String(length=50), nullable=True),
    sa.Column('business', sa.String(length=50), nullable=True),
    sa.Column('log_user', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('log_params', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_permission',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('model_order', sa.Integer(), nullable=True),
    sa.Column('model_level', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('has_child', sa.Integer(), nullable=True),
    sa.Column('permission_type', sa.Integer(), nullable=True),
    sa.Column('create_user', sa.String(length=100), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('update_user', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=True),
    sa.Column('role_desc', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('pers_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('nick_name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('login_ip', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('sys_user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_customer_user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('amounts', sa.DECIMAL(precision=13, scale=2), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_account')
    )
    op.create_table('t_dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dic_key', sa.String(length=255), nullable=True),
    sa.Column('dic_value', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_game_platform_order',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('notify_url', sa.String(length=255), nullable=True),
    sa.Column('method_id', sa.String(length=255), nullable=True),
    sa.Column('bank_id', sa.String(length=255), nullable=True),
    sa.Column('sign', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('notify_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_group',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('str_values', sa.String(length=1000), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('create_user', sa.String(length=20), nullable=True),
    sa.Column('update_user', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_lookup_group',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=20), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('parent_group_code', sa.String(length=50), nullable=True),
    sa.Column('create_user', sa.String(length=20), nullable=True),
    sa.Column('update_user', sa.String(length=20), nullable=True),
    sa.Column('udpate_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('t_lookup_item',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('item_name', sa.String(length=50), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('group_code', sa.String(length=20), nullable=True),
    sa.Column('parent_item_code', sa.String(length=20), nullable=True),
    sa.Column('attribute_1', sa.String(length=100), nullable=True),
    sa.Column('attribute_2', sa.String(length=100), nullable=True),
    sa.Column('attribute_3', sa.String(length=100), nullable=True),
    sa.Column('attribute_4', sa.String(length=100), nullable=True),
    sa.Column('attribute_5', sa.String(length=100), nullable=True),
    sa.Column('create_user', sa.String(length=20), nullable=True),
    sa.Column('update_user', sa.String(length=20), nullable=True),
    sa.Column('udpate_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_order',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('order_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.Column('order_desc', sa.String(length=255), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('user_ip', sa.String(length=50), nullable=True),
    sa.Column('payment_code', sa.String(length=255), nullable=True),
    sa.Column('pay_code', sa.String(length=100), nullable=True),
    sa.Column('pay_order', sa.String(length=255), nullable=True),
    sa.Column('item_code', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rate_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('lock_id', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('t_order_his',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('order_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.Column('order_desc', sa.String(length=255), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('user_ip', sa.String(length=50), nullable=True),
    sa.Column('payment_code', sa.String(length=255), nullable=True),
    sa.Column('pay_code', sa.String(length=100), nullable=True),
    sa.Column('pay_order', sa.String(length=255), nullable=True),
    sa.Column('item_code', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rate_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('lock_id', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('update_user', sa.String(length=30), nullable=True),
    sa.Column('batch_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('t_pay_api',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_code', sa.String(length=20), nullable=False),
    sa.Column('payment_name', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('memberid', sa.String(length=50), nullable=True),
    sa.Column('api_key', sa.String(length=2000), nullable=True),
    sa.Column('http_url', sa.String(length=100), nullable=True),
    sa.Column('http_type', sa.String(length=10), nullable=True),
    sa.Column('notify_url', sa.String(length=100), nullable=True),
    sa.Column('notify_type', sa.String(length=16), nullable=True),
    sa.Column('callback_url', sa.String(length=100), nullable=True),
    sa.Column('query_url', sa.String(length=100), nullable=True),
    sa.Column('sign_type', sa.String(length=50), nullable=True),
    sa.Column('sign_format', sa.String(length=2000), nullable=True),
    sa.Column('param_format', sa.String(length=2000), nullable=True),
    sa.Column('verify_format', sa.String(length=2000), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('attribute_1', sa.String(length=400), nullable=True),
    sa.Column('attribute_2', sa.String(length=400), nullable=True),
    sa.Column('attribute_3', sa.String(length=1000), nullable=True),
    sa.Column('attribute_4', sa.String(length=2000), nullable=True),
    sa.Column('attribute_5', sa.String(length=2000), nullable=True),
    sa.Column('create_user', sa.String(length=20), nullable=True),
    sa.Column('update_user', sa.String(length=20), nullable=True),
    sa.Column('udpate_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_code')
    )
    op.create_table('t_pay_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('pay_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_pay_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_code', sa.String(length=20), nullable=True),
    sa.Column('payment_name', sa.String(length=50), nullable=True),
    sa.Column('pay_code', sa.String(length=225), nullable=True),
    sa.Column('item_name', sa.String(length=50), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('pay_model', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('rate_type', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('min_switch', sa.String(length=4), nullable=True),
    sa.Column('min_amount', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('max_amount', sa.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('max_switch', sa.String(length=4), nullable=True),
    sa.Column('point_switch', sa.String(length=4), nullable=True),
    sa.Column('bank_code', sa.String(length=32), nullable=True),
    sa.Column('create_user', sa.String(length=20), nullable=True),
    sa.Column('update_user', sa.String(length=20), nullable=True),
    sa.Column('udpate_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('white_black_list',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('role_type', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('create_user', sa.String(length=255), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('update_user', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('white_black_list')
    op.drop_table('t_pay_info')
    op.drop_table('t_pay_code')
    op.drop_table('t_pay_api')
    op.drop_table('t_order_his')
    op.drop_table('t_order')
    op.drop_table('t_lookup_item')
    op.drop_table('t_lookup_group')
    op.drop_table('t_group')
    op.drop_table('t_game_platform_order')
    op.drop_table('t_dictionary')
    op.drop_table('t_customer_user')
    op.drop_table('sys_user_role')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('sys_log')
    # ### end Alembic commands ###
